ProjektUmowy/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('umowy.urls')),
]

umowy/urls.py
from django.urls import include,path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


from django.contrib.auth.decorators import login_required

app_name = 'umowy'

urlpatterns = [
    # ex: /
    path('',login_required(views.IndexView.as_view()),name='index'),
    path('login/',auth_views.login,name='login'),
    path('logout/',auth_views.logout,{'next_page':'umowy:login'},name='logout'),

    # /register
    path('register/', views.UserFormView.as_view(),name='user_register'),

    # ex: /systemy/
    path('systemy-lista/',login_required(views.SystemListView.as_view()),name='systemy_list'),
    # ex: /systemy/5/
    path ('systemy/<int:pk>/', login_required(views.SystemDetailView.as_view()),name='systemy_detail'),
    # ex: /systemy/add/
    path ('systemy/add/',login_required(views.SystemCreateView.as_view()),name='systemy_add'),
    # ex: /systemy/12/edit
    path('systemy/<int:pk>/edit/',login_required(views.SystemUpdateView.as_view()),name='systemy_update'),
    # ex: /systemy/12/delete
    path('systemy/<int:pk>/delete/',login_required(views.SystemDeleteView.as_view()),name='systemy_delete'),

    # ex: /umowy/
    path('umowy/',login_required(views.UmowyListView.as_view()),name='umowy_list'),
    # ex: /systemy/5/
    path('umowy/<int:pk>/', login_required(views.UmowyDetailView.as_view()),name='umowy_detail'),
    # ex: /umowy/add/
    path('umowy/add/', login_required(views.UmowyCreateView.as_view()), name='umowy_add'),
    # ex: /umowy/12/edit
    path('umowy/<int:pk>/edit/',login_required(views.UmowyUpdateView.as_view()),name='umowy_update'),
    # ex: /umowy/12/delete
    path('umowy/<int:pk>/delete/',login_required(views.UmowyDeleteView.as_view()),name='umowy_delete'),

    # ex: administracja/bazy/
    path('administracja/bazy/',login_required(views.BazyDanychListView.as_view()),name='bazy_list'),
    # ex: administracja/bazy/1/
    path('administracja/bazy/<int:pk>/',login_required(views.BazyDanychDetailView.as_view()),name='bazy_detail'),
    # ex: administracja/bazy/add
    path('administracja/bazy/add/',login_required(views.BazyDanychCreateView.as_view()),name='bazy_add'),
    # ex: administracja/baze/124/edit/
    path('administracja/bazy/<int:pk>/edit',login_required(views.BazyDanychUpdateView.as_view()),name='bazy_update'),
    # ex: administracja/bazy/12/delete
    path('administracja/bazy/<int:pk>/delete',login_required(views.BazyDanychDeleteView.as_view()),name='bazy_delete'),

    # ex: administracja/administratorzy/
    path('administracja/administratorzy/',login_required(views.AdministratorzyListView.as_view()),name='administratorzy_list'),
    # ex: administracja/administratorzy/1/
    path('administracja/administratorzy/<int:pk>/',login_required(views.AdministratorzyDetailView.as_view()),name='administratorzy_detail'),
    # ex: administracja/administratorzy/add
    path('administracja/administratorzy/add/',login_required(views.AdministratorzyCreateView.as_view()),name='administratorzy_add'),
    # ex: administracja/administratorzy/124/edit/
    path('administracja/administratorzy/<int:pk>/edit',login_required(views.AdministratorzyUpdateView.as_view()),name='administratorzy_update'),
    # ex: administracja/administratorzy/12/delete
    path('administracja/administratorzy/<int:pk>/delete',login_required(views.AdministratorzyDeleteView.as_view()),name='administratorzy_delete'),
    
    # ex: administracja/serwery/
    path('administracja/serwery/',login_required(views.SerweryListView.as_view()),name='serwery_list'),
    # ex: administracja/serwery/1/
    path('administracja/serwery/<int:pk>/',login_required(views.SerweryDetailView.as_view()),name='serwery_detail'),
    # ex: administracja/serwery/add
    path('administracja/serwery/add/',login_required(views.SerweryCreateView.as_view()),name='serwery_add'),
    # ex: administracja/serwery/124/edit/
    path('administracja/serwery/<int:pk>/edit',login_required(views.SerweryUpdateView.as_view()),name='serwery_update'),
    # ex: administracja/serwery/12/delete
    path('administracja/serwery/<int:pk>/delete',login_required(views.SerweryDeleteView.as_view()),name='serwery_delete'),
    
    # ex: administracja/serwerysystemow/
    path('administracja/serwerysystemow/',login_required(views.SerwerySystemowListView.as_view()),name='serwerysystemow_list'),
    # ex: administracja/serwerysystemow/1/
    path('administracja/serwerysystemow/<int:pk>/',login_required(views.SerwerySystemowDetailView.as_view()),name='serwerysystemow_detail'),
    # ex: administracja/serwerysystemow/add
    path('administracja/serwerysystemow/add/',login_required(views.SerwerySystemowCreateView.as_view()),name='serwerysystemow_add'),
    # ex: administracja/serwerysystemow/124/edit/
    path('administracja/serwerysystemow/<int:pk>/edit',login_required(views.SerwerySystemowUpdateView.as_view()),name='serwerysystemow_update'),
    # ex: administracja/serwerysystemow/12/delete
    path('administracja/serwerysystemow/<int:pk>/delete',login_required(views.SerwerySystemowDeleteView.as_view()),name='serwerysystemow_delete'),



]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    

umowy/models.py
from django.db import models
from django.shortcuts import reverse
from django.db import models
############################################################################################################################
## BAZY DANYCH ##
############################################################################################################################
class BazyDanych(models.Model):
    ORACLE = 'Or'
    MYSQL = 'My'
    POSTGRESQL = 'Po'
    MSSQL = 'Ms'
    DB_CHOICES = (
        (ORACLE, 'Oracle'),
        (MYSQL, 'MySQL'),
        (POSTGRESQL, 'PostgreSQL'),
        (MSSQL, 'MS SQL'),
    )
    PLATNA = 'Pl'
    DARMOWA = 'Da'
    LICENCJA_CHOICES = (
        (PLATNA, 'Płatna'),
        (DARMOWA, 'Darmowa'),
    )
    nazwa = models.CharField(
        max_length=2,
        choices = DB_CHOICES,
        default=MYSQL,
    )
    wersja = models.CharField(max_length=40)
    licencja = models.CharField(
        max_length=2,
        choices = LICENCJA_CHOICES,
        default = DARMOWA
    )
    def __str__(self):
        return self.nazwa + " " + self.wersja
    def get_absolute_url(self):
        return reverse('umowy:bazy_detail',kwargs={'pk':self.pk})

############################################################################################################################
## ADMINISTRATORZY ##
############################################################################################################################

class Administratorzy(models.Model):
    imie = models.CharField(max_length=100)
    nazwisko = models.CharField(max_length=100)
    def __str__(self):
        return self.imie + " " + self.nazwisko
    def get_absolute_url(self):
        return reverse('umowy:administratorzy_detail',kwargs={'pk':self.pk})
############################################################################################################################
## SERWERY ##
############################################################################################################################
class Serwery(models.Model):
    LINUX = 'L'
    WINDOWS = 'W'
    SYSTEM_CHOICES = (
        (LINUX, 'Linux'),
        (WINDOWS, 'Windows'),
    )
    FIZYCZNY = 'F'
    WIRTUALNY = 'W'
    WIFI_CHOICES = (
        (FIZYCZNY,'Fizyczny'),
        (WIRTUALNY,'Wirtualny'),

    )
    hostname = models.CharField(max_length=100, unique=True)
    nazwa = models.CharField(max_length=100)
    system_operacyjny = models.CharField(
        max_length=1,
        choices = SYSTEM_CHOICES,
        default = WINDOWS,
    )
    fizyczny_wirtualny = models.CharField(
        max_length=1,
        choices = WIFI_CHOICES,
        default = FIZYCZNY,
    )
    wersja = models.CharField(max_length=40)
    adres = models.CharField(max_length=15)
    def __str__(self):
        return self.nazwa + " " + self.wersja
    def get_absolute_url(self):
        return reverse('umowy:serwery_detail',kwargs={'pk':self.pk})


############################################################################################################################
## SYSTEMY ##
############################################################################################################################
class Systemy(models.Model):
    INSTYTUT = 'IB'
    SPOLKA = 'SP'
    FIRMA_CHOICES = (
        (INSTYTUT, 'NASK PIB'),
        (SPOLKA, 'NASK SA'),
    )
    firma = models.CharField(
        max_length=2,
        choices = FIRMA_CHOICES,
        default = INSTYTUT,
    )
    nazwa = models.CharField(max_length=100)
    opis_systemu = models.TextField(max_length=400)
    baza_danych = models.ForeignKey(BazyDanych,blank=True, null=True,on_delete=models.SET_NULL)
    oprogramowanie = models.CharField(max_length=100,blank=True)
    data_wsparcia = models.DateField('data końca wsparcia')
    administrator_systemu_glowny = models.ForeignKey(Administratorzy,blank=True, null=True,on_delete=models.SET_NULL, related_name='admin_system_glowny')
    administrator_systemu_zastepczy = models.ForeignKey(Administratorzy,blank=True, null=True,on_delete=models.SET_NULL, related_name='admin_system_zastepca')
    administrator_bazy_glowny = models.ForeignKey(Administratorzy,blank=True, null=True,on_delete=models.SET_NULL, related_name='admin_baza_glowny')
    administrator_bazy_zastepczy = models.ForeignKey(Administratorzy,blank=True, null=True,on_delete=models.SET_NULL, related_name='admin_baza_zastepca')
    def get_absolute_url(self):
        return reverse('umowy:systemy_detail',kwargs={'pk':self.pk})
    def __str__(self):
        return self.nazwa

############################################################################################################################
## UMOWY UTRZYMANIOWE ##
############################################################################################################################

class UmowyUtrzymaniowe(models.Model):
    opis = models.CharField(max_length=100)
    dataUmowy = models.DateField('Data podpisania')
    dataKoncaUmowy = models.DateField('Data końca obowiązywania')
    wsparcie_techniczne = models.TextField(max_length=400)
    system = models.ForeignKey(Systemy, on_delete=models.CASCADE)
    plik_umowy = models.FileField()
    def get_absolute_url(self):
        return reverse('umowy:umowy_detail',kwargs={'pk':self.pk})
    def __str__(self):
        return self.opis

############################################################################################################################
## SERWERY SYSTEMÓW ##
############################################################################################################################
class SerwerySystemow(models.Model):
    serwer = models.ForeignKey(Serwery,blank=True, null=True,on_delete=models.SET_NULL)
    system = models.ForeignKey(Systemy,blank=True, null=True,on_delete=models.SET_NULL)
    def get_absolute_url(self):
        return reverse('umowy:serwerysystemow_detail',kwargs={'pk':self.pk})

umowy/forms.py
from .models import Systemy,UmowyUtrzymaniowe
from django import forms

from django.contrib.auth.models import User


class SystemForm(forms.ModelForm):
    class Meta:
        model = Systemy
        fields = ['nazwa','opis_systemu','firma','baza_danych','oprogramowanie','data_wsparcia','administrator_systemu_glowny','administrator_systemu_zastepczy','administrator_bazy_glowny','administrator_bazy_zastepczy']
        widgets = {
            'data_wsparcia': forms.SelectDateWidget(),
            'opis_systemu': forms.Textarea(attrs={'cols':60,'rows':5}),

        }
        labels = {
            'nazwa':'Nazwa systemu',
            'opis_systemu': 'Opis systemu',
            'baza_danych': 'Baza danych na jakiej oparty jest system',
            'oprogramowanie': 'Oprogramowanie do systemu',
            'administrator_systemu_glowny': 'Administrator główny systemu',
            'administrator_systemu_zastepczy': 'Administrator zastępczy systemu',
            'administrator_bazy_glowny':'Administrator główny bazy danych',
            'administrator_bazy_zastepczy':'Administrator zastępczy bazy danych',

        }
        #error_messages = {
        #    NON_FIELD_ERRORS: {
        #
        #    }
        #}

class UmowaForm(forms.ModelForm):
    class Meta:
        model = UmowyUtrzymaniowe
        fields = ['opis','dataUmowy','dataKoncaUmowy','wsparcie_techniczne','system','plik_umowy']
        widgets = {
            'dataUmowy': forms.SelectDateWidget(),
            'dataKoncaUmowy': forms.SelectDateWidget()
        }
    




    #class Meta:
    #    model = Systemy
    #   fields = ['nazwa','opis_systemu','baza_danych','oprogramowanie','data_wsparcia']

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password']
        widgets = {
            'password': forms.PasswordInput(),
        }

umowy/templates/umowy/administratorzy_detail.html
{% extends "umowy/home.html" %}
{% block content %}
<h1>{{ object.imie }} {{ object.nazwisko }}</h1>
<ul>
    
</ul>
{% endblock %}

umowy/templates/umowy/administratorzy_form.html
{% extends "umowy/home.html" %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12" "col-md-7">
                <div class = "panel panel-default">
                    <div class = "panel-body">
                        <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'umowy/administratorzy-form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">

                                    <button type="submit" class="btn btn-success">Wprowadź</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
        
{% endblock %}

umowy/templates/umowy/administratorzy_list.html
{% extends "umowy/home.html" %}
{% block content %}
{% if administratorzy_list %}
    <table class="table table-bordered table-hover">
        <thread>
            <tr>
                <th>ID</th>
                <th>Imię</th>
                <th>Nazwisko</th>
            </tr>
        </thread>
        <tbody>
            {% for admin in administratorzy_list %}
            <tr>
                <td>{{admin.id}}</td>
                <td><a href="{% url 'umowy:administratorzy_detail' admin.id %}">{{admin.imie}} {{admin.nazwisko}}</a></td>
                <td>{{admin.imie}}</td>
                <td>{{admin.nazwisko}}</td>
                <td>
                    <a href="{% url 'umowy:administratorzy_update' admin.id %}" class="btn btn-primary btn-block">Edycja</a>
                </td>
                <td>
                    <form action="{% url 'umowy:administratorzy_delete' admin.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="admin_id" value="{{ admin.id }}"/>
                        <button type="submit" class="btn btn-danger btn-block" onclick="return confirm('Czy chcesz usunąć?')">Usuń</button>
                    </form>
                </td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>Brak administratorów do wyświetlenia.</p>

{% endif %}
{% endblock %}

umowy/templates/umowy/bazy-form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-4" "col-sm_10">
            <span class="text-danger small">{{ field.errors }}</span>

        </div>
        <label class="control-label col-sm-4">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

umowy/templates/umowy/bazy_detail.html
{% extends "umowy/home.html" %}
{% block content %}
<h1>{{ object.get_nazwa_display }}</h1>
<ul>
    <li>{{object.wersja}}</li>
    <li>{{object.get_licencja_display}}</li>
</ul>
{% endblock %}

umowy/templates/umowy/bazy_form.html
{% extends "umowy/home.html" %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12" "col-md-7">
                <div class = "panel panel-default">
                    <div class = "panel-body">
                        <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'umowy/bazy-form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">

                                    <button type="submit" class="btn btn-success">Wprowadź</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
        
{% endblock %}

umowy/templates/umowy/home.html
<!DOCTYPE html>
<html lang="pl">
    <head>
        <title> Repozytorium umów </title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'umowy/css/bootstrap.min.css' %}" type="text/css" />
        <link rel="stylesheet" href="{% static 'umowy/css/sticky-footer-navbar.css' %}" type="text/css" />
    </head>
    <body class="body" style="background-color:rgba(157, 191, 245, 0.562)">
            <header>
                <!-- Fixed navbar -->
                <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
                    <a class="navbar-brand" href="{% url 'umowy:index' %}">Repozytorium</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    {% if user.is_authenticated %}
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav mr-auto">
                            <li class="dropdown">
                                <a class="nav-link" href="{% url 'umowy:systemy_list' %}" data-toggle="dropdown">Systemy<span class="sr-only"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'umowy:systemy_list' %}">Lista</a></li>
                                    <li><a  class="dropdown-item" href="{% url 'umowy:systemy_add' %}">Dodaj nowy system</a></li>
                                    <li><a  class="dropdown-item" href="{% url 'umowy:serwerysystemow_list' %}"> Serwery systemów lista</a></li>
                                    <li><a  class="dropdown-item" href="{% url 'umowy:serwerysystemow_add' %}">Przypisz serwer do systemu</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                            <a class="nav-link" href="{% url 'umowy:umowy_list' %}" data-toggle="dropdown">Umowy<span class="sr-only"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a  class="dropdown-item" href="{% url 'umowy:umowy_list' %}">Lista</a></li>
                                    <li><a  class="dropdown-item" href="{% url 'umowy:umowy_add' %}">Dodaj nową umowę</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                    <a class="nav-link" href="#" data-toggle="dropdown">Administracja<span class="sr-only"></span></a>
                                        <ul class="dropdown-menu">
                                            <li><a  class="dropdown-item" href="{% url 'umowy:bazy_list' %}">Bazy danych lista</a></li>
                                            <li><a  class="dropdown-item" href="{% url 'umowy:bazy_add' %}">Dodaj nową bazę</a></li>
                                            <li><a  class="dropdown-item" href="{% url 'umowy:administratorzy_list' %}">Administratorzy lista</a></li>
                                            <li><a  class="dropdown-item" href="{% url 'umowy:administratorzy_add' %}">Dodaj nowego administratora</a></li>
                                            <li><a  class="dropdown-item" href="{% url 'umowy:serwery_list' %}">Serwery lista</a></li>
                                            <li><a  class="dropdown-item" href="{% url 'umowy:serwery_add' %}">Dodaj nowy serwer</a></li>
                                        </ul>
                                    </li>
                            <li class="dropdown ">
                                    <a class="nav-link" href="#" data-toggle="dropdown">{{request.user.first_name}} {{request.user.last_name}}<span class="sr-only"></span></a>
                                    <ul class="dropdown-menu">
                                            
                                            <li><a class="dropdown-item"href="{% url 'umowy:logout' %}">Logout</a></li>
                                            
                                    </ul>
                            </li>
                        </ul>
                    </div>
                    {% endif %}
                </nav>
            </header>
            <!-- Begin page content -->
            <main role="main" class="container-fluid">
                {% block content %}
                {% endblock %}
            </main>
            <footer class="footer">
                <div class="container">
                    <span class="text-muted">ZSW - Repozytorium umów .</span>
                </div>
            </footer>
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->    
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    </body>
</html>

umowy/templates/umowy/index.html
{% extends "umowy/home.html" %}
{% block content %}
{% if latest_system_list %}
    <ul>
        {% for system in latest_system_list %}
        <li><a href="{% url 'umowy:systemy_detail' system.id %}">{{system.nazwa}}</a></li>
        {% endfor %}
    
    </ul>
{% else %}
    <p>Brak systemów do wyświetlenia.</p>

{% endif %}
{% endblock %}

umowy/templates/umowy/search-form.html
<form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>

umowy/templates/umowy/serwerysystemow_detail.html
{% extends "umowy/home.html" %}
{% block content %}
<ul>
    
    <li> {{ object.id }}</li>
    <li> {{ object.serwer }}</li>
    <li> {{ object.system }}</li>
    
</ul>
{% endblock %}

umowy/templates/umowy/system-form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-4" "col-sm_10">
            <span class="text-danger small">{{ field.errors }}</span>

        </div>
        <label class="control-label col-sm-4">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

umowy/templates/umowy/systemy_form.html
{% extends "umowy/home.html" %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12" "col-md-7">
                <div class = "panel panel-default">
                    <div class = "panel-body">
                        <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'umowy/system-form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">

                                    <button type="submit" class="btn btn-success">Wprowadź</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
        
{% endblock %}

umowy/templates/umowy/umowa_form_add.html
{% extends "umowy/home.html" %}
{% block content %}
<div class="container">
    <h1>Dodaj nową Umowę</h1>
    <form class="form-horizontal" action= "" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label class="col-sm-5 control-label" for="opis">Opis umowy:</label>
            <div class="col-sm-10">
                <input class="form-control" name="opis" id="opis" type="text" placeholder="Wpisz opis umowy" autofocus required />
            </div>
            <label class="col-sm-5 control-label" for="dataUmowy">Data podpisania umowy:</label>
            <div class="col-sm-10">
                <input class="form-control" name="dataUmowy" id="dataUmowy" type="date" placeholder="Wprowadź datę podpisania umowy" required />
            </div>
            <label class="col-sm-5 control-label" for="dataKoncaUmowy">Data końca obowiązywania umowy:</label>
            <div class="col-sm-10">
                <input class="form-control" name="dataKoncaUmowy" id="dataKoncaUmowy" type="date" required placeholder="Wprowadź datę końca obowiązywania umowy" />
            </div>
            <label class="col-sm-5 control-label" for="wsparcie_techniczne">Wsparcie techniczne dla systemu:</label>
            <div class="col-sm-10">
                <input class="form-control" name="wsparcie_techniczne" id="wsparcie_techniczne" required type="text" placeholder="Dane wsparcia technicznego" />
            </div>
            <label class="col-sm-5 control-label" for="system">Jakiego systemu dotyczy umowa:</label>
            <div class="col-sm-10">
                <select name="system" id="system">
                
                {% for obj in form.systemy %}
                <option value ="{{obj}}">{{obj }}</option>
                {% endfor %}
            </select>
            </div><br />
            <div class="col-sm-3">
                <input class="btn btn-primary" type="submit" value="Wprowadź" />
             </div>
        </div>
               
    </form>
</div>



{% endblock %}

umowy/templates/umowy/umowy_list.html
{% extends "umowy/home.html" %}
{% block content %}
{% if umowy_list %}
    <table class="table table-bordered">
        <thread>
            <tr>
                <th>id</th>
                <th>Opis</th>
                <th>Data umowy</th>
                <th>Data końca umowy</th>
                <th>Wsparcie techniczne</th>
                <th>System</th>
                <th>Plik umowy</th>
                <th>Edycja</th>
                <th>Usuń</th>
            </tr>
        </thread>
        <tbody>
            {% for umowa in umowy_list %}
            <tr>
                <td>{{umowa.id}}</td>
                <td><a href="{% url 'umowy:umowy_detail' umowa.id %}">{{umowa.opis}}</a></td>
                <td>{{umowa.dataUmowy|date:"d E, Y"}}</td>
                <td>{{umowa.dataKoncaUmowy|date:"d E, Y"}}</td>
                <td>{{umowa.wsparcie_techniczne}}</td>
                <td><a href="{% url 'umowy:systemy_detail' umowa.system.id %}">{{umowa.system}}</a></td>
                <td><a href="{{ umowa.plik_umowy.url }}" target="_blank" class="btn btn-info btn-block">{{ umowa.plik_umowy }}</a></td>
                <td>
                        <a href="{% url 'umowy:umowy_update' umowa.id %}" class="btn btn-primary btn-block">Edycja</a>
                    </td>
                    <td>
                        <form action="{% url 'umowy:umowy_delete' umowa.id %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="umowa_id" value="{{ umowa.id }}"/>
                            <button type="submit" class="btn btn-danger btn-block" onclick="return confirm('Czy chcesz usunąć?')">Usuń</button>
                        </form>
                    </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>Brak umów do wyświetlenia.</p>

{% endif %}
{% endblock %}